# Generated by Django 4.1.7 on 2023-03-22 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_fotografia_criado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='criado_em',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 22, 15, 28, 9, 71993)),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/'),
        ),
    ]
